In [1]:
import numpy as np
# numpy has vector (1d array) , matrix (2d array)
my_list = [1,2,3] # this is python list
np.array(my_list) # convert python list to numpy array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # convert python lists to numpy matrix
np.arange(0,10) #  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(0,11,2) # array([ 0,  2,  4,  6,  8, 10])
np.zeros(3) #array([ 0.,  0.,  0.])
print(np.zeros((3,4)))
print(np.ones(4))
np.ones((3,3)) # all 1's 
np.linspace(0,10,50) # 
np.eye(3) # Identity Matrix
np.random.rand(4) # all elements are [0:1] random
np.random.randn(2) # normally distributed with u = 0 , sd =1 
np.random.randn(3,4)
np.random.randint(1,100) # scaled random number between 1-100
np.random.randint(1,100,10) # 10-element array

arr = np.arange(25).reshape(5,5)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1.]


In [21]:
arr = np.arange(25).reshape(5,5) # allocate a 25-length array and then make it matrix by 5*5
arr 
# ranarr.max() max value ,ranarr.argmax() index of max value,ranarr.min(),ranarr.argmin()
arr.shape
arr.dtype # gives data type
oneDArray = np.array([3,4,5,6,7])

twoDArray = np.array(([3,4,5,6,7],[11,23,44,55,22],[30,40,50,60,70],[33,43,53,63,73]))

oneDArray[1] # 4  index starts from zero
oneDArray[-1] # 7 last item , -2 for second last item
oneDArray[2:4]  # array([5, 6]) , last one exclusive 
oneDArray[2:4] = 99 # we call this broadcasting

oneDArray[:]=99 # all elements
arr_copy = arr.copy() # deep copy , = is just shallow copy
twoDArray[1] # select the second row [11,23,44,55,22]
twoDArray[1][2] # second row , third element = 44
twoDArray[1,2] # same as above 
twoDArray[1,2:4] # same as above [44,55]
twoDArray[0:2,2:4] #array([[ 5,  6],[44, 55]])
twoDArray[:2,1:]#array([[ 4,  5,  6,  7], [23, 44, 55, 22]])
twoDArray[2,:] # select all 
twoDArray[[0,1]] # select first and second row of the matrix
twoDArray[[2,1]] 
twoDArray.shape #(4,5), no of row twoDArray.shape[0], no of column twoDArray.shape[1]
twoDArray[1] =4 # set all elements of row 2 to be 4 


array([False,  True,  True])

In [23]:
# Array Selection 
arr2 = np.array([1,7,8])
arr2 > 5 # array([False,  True,  True])
arr2[arr2>2] # array([7, 8])




array([7, 8])

In [26]:
import numpy as np
arr1 = np.arange(0,10)
arr2 = np.arange(10,20)
arr2 + arr1 # elementwise addition 
arr2 * arr1 # elementwise multiplication , 
arr1/arr1 # elementwise division, nan for div by zero, just warning 
1/arr # elementwise reciprocal
# some maths function np.sqrt(arr)/np.exp(arr)/np.max(arr)/np.sin(arr)/np.log(arr)
s

<ipython-input-26-4339b022eeb2>:6: RuntimeWarning: invalid value encountered in true_divide
  arr1/arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [29]:
# transpose
import numpy as np
x = np.array(([3,4,5,6,7],[11,23,44,55,22],[30,40,50,60,70],[33,43,53,63,73]))
x.transpose()


array([[ 3, 11, 30, 33],
       [ 4, 23, 40, 43],
       [ 5, 44, 50, 53],
       [ 6, 55, 60, 63],
       [ 7, 22, 70, 73]])

In [33]:
# matrix multiplication
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.multiply(arr1, arr2)
arr1*arr2 # elementwise matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [49]:
# Linear Algebra (I) :
a = np.empty([3,3]) # another way to initialize an array other than zeros()
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.vstack((a1, a2)) # array([[1, 2, 3],[4, 5, 6]])
np.hstack((a1, a2)) # array([1, 2, 3, 4, 5, 6])



data = np.array([1,2,3,4])
a2 = np.array([4,5,6,7])
data.reshape((data.shape[0], 1))  # array([[1],[2],[3],[4]])
A = np.array([
[1, 2, 3],
[4, 5, 6]])
A + 2 # elementwise + 2


array([[3, 4, 5],
       [6, 7, 8]])

In [51]:
# Linear Algebra : Vector 
a = np.array([1, 2, 3])
b = np.array([10,30, 30])
a+b # vector addition 
a*b # vector multiplication (elementwise)
a.dot(b) # 160 , dot product of vector 



AttributeError: module 'numpy' has no attribute 'norm'

In [53]:
from numpy.linalg import norm
norm(a) # 3.7416573867739413 


3.7416573867739413

In [67]:
A = np.array([[1, 2, 3], [20, 30, 40],[1,2,1]])
B = np.array([[1, 2, 3], [0,0,0],[1,3,3]])
v = np.array([3,4,5])
A+B # basic matrix addition ( elementwise)
A * B # elementwise matrix multiplication
A.dot(B) # AB 

A.dot(v) # Av (3*3)(1*3) ? , seems numpy does not differentiate row vector or column vector
print("Shapes", A.shape, v.shape, A.dot(v).shape)

A = np.array([[1, 2, 3], [20, 30, 40]])

print("Shapes", A.shape, v.shape, A.dot(v).shape) 




Shapes (3, 3) (3,) (3,)
Shapes (2, 3) (3,) (2,)


AttributeError: module 'numpy' has no attribute 'inv'

In [77]:
from numpy.linalg import inv
from numpy.linalg import det
from numpy.linalg import matrix_rank
A = np.array([[1, 2, 3], [20, 30, 40],[1,2,1]])
C = np.array([[0,0,0], [0,0,0],[0,0,0]])
B = np.array([[1, 2, 3], [20, 30, 40]])
# np.tril(A), makes it a lower triangular matrix np.triu(A),
# np.diag(M), makes it a diagonal matrix
# I = np.identity(4) 
inv(A) # inverse of matrix A
# inv(B) , LinAlgError ( not square)
# inv(C) , LinAlgError (singular matrix)
A.T # transpose of A
np.trace(A) # get the trace(A), summation of diagonals
det(A) # get the determinant of A
matrix_rank(A) # get the number of rank of matrix A


3