ref : https://www.tensorflow.org/tutorials/quickstart/beginner 
For learning TF with 

In [2]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# print(type(x_train)) # numpy.ndarray
# print(x_train.shape) #(60000, 28, 28), meaning, 60000 samples, 28x28 
x_train, x_test = x_train / 255.0, x_test / 255.0
#Normalize the data to from 0 to 1 using broadcasting

Define the NN structure :<br><br>
Sequential -> steps are run sequentially, one by one<br><br>
Flatten -> convert (28,28) data into (28*28,1) data<br><br>
Using relu as activation function, other options(tanh, sigmoid{not-so-good for stabilizing gradient})<br><br>
Dropout -> using Dropout at prob. 0.2 , to reduce overfitting.<br><br>
Dense -> fully connected layer with 128 neurons<br><br>
ref : https://sparrow.dev/keras-dense-layer/ <br><br>





In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


- x_train is (60000,28,28), x_train[:1] is (1,28,28)
- predictions is returned in log odds (i.e. log(p/(1-p)) )
- This predictions is fed to the last softmax layer which take log-odds as input. 
- softmax() converts log odds(logits) to normal probability
- numpy() convert data from tensor data type to numpy data type


In [5]:

print(x_train[:1].shape)

predictions = model(x_train[:1]).numpy() # note this model is untrained yet!!!!
print(predictions)

tf.nn.softmax(predictions).numpy()


(1, 28, 28)
[[ 0.14525738  0.44951153 -0.35766387 -0.17903815 -0.33537504  0.29884958
  -0.11013418  0.4570856  -0.30038756  0.43196672]]


array([[0.10437541, 0.14149272, 0.06312223, 0.07546723, 0.06454494,
        0.12170333, 0.08085057, 0.14256847, 0.06684317, 0.13903192]],
      dtype=float32)

- This define a loss function in Cross-entropy:
- Least Square is an example of loss function, we want to find parameters to minimize the loss
- Cross Entropy is the loss function for NN which compare the difference between 2 distributions, probably from hypothesis and sample distrbutions. 
- from_logits=True, input as logits

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# loss_fn(y_train[:1], predictions).numpy() # example of running 

define the model :

- adam is the momentum based technique used in gradient descent to improve the speed of finding minimum, ref : https://machinelearningmastery.com/adam-optimization-algorithm-for-deep-learning/ 
- epoch is the number of times of feeding the full training set to the model 
https://towardsdatascience.com/epoch-vs-iterations-vs-batch-size-4dfb9c7ce9c9  , too low -> underfit, too high -> overfit



In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5) # This step perform real training

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2902 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1408 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1063 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0879 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0751 - accuracy: 0.9764


In [8]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0707 - accuracy: 0.9774


[0.07074465602636337, 0.977400004863739]

In [9]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.78269346e-07, 2.19373564e-09, 1.62400568e-06, 2.79981003e-04,
        1.78932823e-12, 1.45183733e-07, 1.60922470e-14, 9.99708354e-01,
        2.55418485e-07, 9.50978483e-06],
       [7.81954952e-07, 6.09106850e-04, 9.99252975e-01, 1.34972550e-04,
        4.04219193e-13, 1.35531320e-06, 1.30613870e-07, 7.09345693e-09,
        5.84360635e-07, 5.83340139e-14],
       [1.16320365e-07, 9.99193847e-01, 9.31574832e-05, 1.79182712e-06,
        1.43747766e-05, 1.63772529e-06, 2.33122591e-05, 6.15166384e-04,
        5.61877132e-05, 4.38096407e-07],
       [9.99908447e-01, 3.33513372e-09, 2.67895630e-05, 1.68876042e-07,
        1.79418453e-06, 1.32241976e-05, 3.64188622e-07, 2.36321807e-06,
        1.68354219e-07, 4.66915371e-05],
       [1.27034179e-08, 1.10635989e-09, 3.56521241e-06, 1.06545792e-06,
        9.99246716e-01, 2.74419875e-07, 4.82346962e-08, 3.75298077e-06,
        3.51200833e-06, 7.41071184e-04]], dtype=float32)>